### ISSUE TITLE
Unauthorized error after sign out 

### ISSUE THREAD

**Issue by fabiancook** [joukou/joukou-api#36]
Steps to reproduce:
Login using github - Returns token
Load personas - Authorized
Signout 
Login using github - Returns token
Load personas - Unauthorized
Reload page
Load personas - Unauthorized
Sign out
Login using github - Returns token
Load personas - Authorized
Reload page
Load personas - Authorized

**Comment by fabiancook** [comment]
@superstructor any ideas?

**Comment by fabiancook** [comment]
Authorization header seems to be different after each request as well...

Not auth

Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZhYmlhbi5jb29rQGpvdWtvdS5jb20iLCJnaXRodWJfbG9naW4iOiJmYWJpYW5jb29rIiwiZ2l0aHViX2lkIjo0MzM3MDgwLCJpbWFnZV91cmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvNDMzNzA4MD92PTMiLCJ3ZWJzaXRlIjoic2hpcHBlci5jby5ueiIsImdpdGh1Yl91cmwiOiJodHRwczovL2FwaS5naXRodWIuY29tL3VzZXJzL2ZhYmlhbmNvb2siLCJuYW1lIjoiRmFiaWFuIENvb2siLCJjb21wYW55IjoiQ2hhcmxlcyBTb2Z0d2FyZSIsImxvY2F0aW9uIjoiTmV3IFplYWxhbmQiLCJpYXQiOjE0MTU3NjA3OTZ9.yaPht8IzdCS7so5ylz5uB_c97RSFoTBlaXwGViWnoHQ

Auth

Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImZhYmlhbi5jb29rQGpvdWtvdS5jb20iLCJnaXRodWJfbG9naW4iOiJmYWJpYW5jb29rIiwiZ2l0aHViX2lkIjo0MzM3MDgwLCJpbWFnZV91cmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvNDMzNzA4MD92PTMiLCJ3ZWJzaXRlIjoic2hpcHBlci5jby5ueiIsImdpdGh1Yl91cmwiOiJodHRwczovL2FwaS5naXRodWIuY29tL3VzZXJzL2ZhYmlhbmNvb2siLCJuYW1lIjoiRmFiaWFuIENvb2siLCJjb21wYW55IjoiQ2hhcmxlcyBTb2Z0d2FyZSIsImxvY2F0aW9uIjoiTmV3IFplYWxhbmQiLCJpYXQiOjE0MTU3NjA4MzF9.DIL2QI1RGr6etcTo9_r7F28wwIK_l8ol2wz1dV-0TCw

**Comment by fabiancook** [comment]
Tracked down to indexes not persisting.

**Comment by fabiancook** [comment]
Add "afterRetrieve" and "beforeSave" methods to the model. In afterRetrieve I make sure the required indexes are there. Otherwise the indexes are only there from AgentModel.afterCreate

**Comment by superstructor** [comment]
Good work!
